name: base
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - archspec=0.2.1=pyhd3eb1b0_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - blas=1.0=mkl
  - boltons=23.0.0=py39haa95532_0
  - brotli-python=1.0.9=py39hd77b12b_7
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.12.12=haa95532_0
  - certifi=2024.2.2=py39haa95532_0
  - cffi=1.16.0=py39h2bbff1b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - conda=24.1.1=py39haa95532_0
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.2.0=py39haa95532_0
  - conda-package-streaming=0.9.0=py39haa95532_0
  - cryptography=41.0.7=py39h89fc84f_0
  - cuda-cccl=12.3.101=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-opencl-dev=12.3.101=0
  - cuda-profiler-api=12.3.101=0
  - cuda-runtime=12.1.0=0
  - debugpy=1.6.7=py39hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - distro=1.8.0=py39haa95532_0
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.13.1=py39haa95532_0
  - fmt=9.1.0=h6d14046_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - gmpy2=2.1.2=py39h7f96b67_0
  - idna=3.4=py39haa95532_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.0=pyha63f2e9_0
  - ipython=8.12.0=pyh08f2357_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py39haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=4.12.0=py39hcbf5309_0
  - lerc=3.0=hd77b12b_0
  - libarchive=3.6.2=hb62f4d4_2
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.4.107=0
  - libcurand-dev=10.3.4.107=0
  - libcurl=8.5.0=h86230a5_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libiconv=1.16=h2bbff1b_2
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libmamba=1.5.6=hcd6fe79_0
  - libmambapy=1.5.6=py39h77c03ed_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h8d14728_1
  - libsolv=0.7.24=h23ce68f_0
  - libssh2=1.10.0=he2ea4bf_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - libxml2=2.10.4=h0ad7f3c_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.3=py39h2bbff1b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - menuinst=2.0.2=py39hd77b12b_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.8=py39h2bbff1b_0
  - mkl_random=1.2.4=py39h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py39haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=py39haa95532_0
  - numpy=1.26.3=py39h055cbcc_0
  - numpy-base=1.26.3=py39h65a83cf_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.0.13=h2bbff1b_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.42=h0ff8eda_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py39h045eedc_0
  - pip=23.3.1=py39haa95532_0
  - platformdirs=3.10.0=py39haa95532_0
  - pluggy=1.0.0=py39haa95532_1
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.0=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py39h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py39haa95532_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.18=h1aa4202_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.2.0=py3.9_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pywin32=227=py39hb82d6ee_1
  - pyyaml=6.0.1=py39h2bbff1b_0
  - pyzmq=25.1.2=py39hd77b12b_0
  - reproc=14.2.4=hd77b12b_1
  - reproc-cpp=14.2.4=hd77b12b_1
  - requests=2.31.0=py39haa95532_0
  - ruamel.yaml=0.17.21=py39h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py39h2bbff1b_1
  - setuptools=68.2.2=py39haa95532_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py39haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.12=h2bbff1b_0
  - torchvision=0.15.2=cpu_py39h7187fe4_0
  - tornado=6.2=py39hb82d6ee_0
  - tqdm=4.65.0=py39hd4e2768_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.9.0=py39haa95532_1
  - urllib3=1.26.18=py39haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xz=5.4.5=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - yaml-cpp=0.8.0=hd77b12b_0
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstandard=0.19.0=py39h2bbff1b_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.48.1
      - fsspec==2024.2.0
      - importlib-resources==6.1.1
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - matplotlib==3.8.2
      - pandas==2.2.2
      - pyparsing==3.1.1
      - pytz==2024.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - threadpoolctl==3.5.0
      - torchaudio==2.2.0
      - torchmetrics==1.4.0.post0
      - tzdata==2024.1
      - wrapt==1.16.0
prefix: C:\Users\Atlas\anaconda3\envs\icenv
